### ISSUE TITLE
Unable to detect/load certain assemblies

### ISSUE THREAD

**Issue by MissSecret** [LeagueSharp/LeagueSharp.Loader#103]
so far only found problems loading EzEvade, DevCassio, GoldenGate's Cassio, BaseUlt (randomly happens)
I was able to load it for 1-2 games and 
then next game suddenly it is not loaded or detected.

edit: it might be happened to random assemblies

**Comment by ChewyMoon** [comment]
This is because the local pipe is still open, close your loader, and restart it.

**Comment by MissSecret** [comment]
@ChewyMoon thanks, someone else tried devcass for first time couldnt load it as well is it of the same reason ?

**Comment by MissSecret** [comment]
extra info: 4-5 people informed that they couldnt even test some assemblies couldnt be injected or loaded at all; 2 ppl reported that some assemblies was running fine for 1 game 

I also updated hellsing kalista with q hitchance small amount of changes- recieved this comment "tried your, doesnt inject :( / the original was able to inject tho"
