### ISSUE TITLE
Cant 'resize' columns unless at the top of assemblies list

### ISSUE THREAD

**Issue by Evil-Master** [LeagueSharp/LeagueSharp.Loader#148]
As stated in the title, the only way I've been able to resize the columns (Name, Type, Version, Location, Description) is if I have the scrollbar at the very top of the list. if I have the list scrolled at all, it appears to want to copy the column name. 

I understand there's a new loader coming out, I have seen it, but perhaps it might suffer from the same 
bug. Either way, if you can look into this great, if not.. no hard feelings, just wanted to report this. :)

![l](https://cloud.githubusercontent.com/assets/1400709/9558227/22b11004-4db1-11e5-8089-7f9711476c25.gif)

**Comment by Screeder** [comment]
Should be fixed now
