### ISSUE TITLE
Fix icon menu saying Hide when LeagueSharp is already hidden

### ISSUE THREAD

**Issue by eddy5641** [LeagueSharp/LeagueSharp.Loader#58]
This is basic and easy to overlook so I thought I would pull this up
To fix just change
<MenuItem Header="Hide" Click="TrayMenuHide_OnClick"/> 
to
<MenuItem x:Name="HideItem" Header="Hide" Click="TrayMenuHide_OnClick"/> 

Also every time Hide() is called use
     HideItem.Header = "Show";

and every time Show() is called use
     HideItem.Header = "Hide";

**Comment by PORNCORE** [comment]
Fixed it in my forked ver so pulled it up

**Comment by eddy5641** [comment]
They fixed it :P
