### ISSUE TITLE
Theme changer

### ISSUE THREAD

**Issue by HyunMi027** [LeagueSharp/LeagueSharp.Loader#74]
I would love to be able to have a change theme button, to change from BaseLight to BaseDark

**Comment by legacy3** [comment]
then code it and pull it :+1:

**Comment by HyunMi027** [comment]
will do, it's prolly just using MahApps.metro right?

**Comment by legacy3** [comment]
yes :+1:

**Comment by HyunMi027** [comment]
h3h3 told me such a feature was already planned
closed
